services:
  - type: web
    name: tikfinity-gift-board
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_TOKEN
        sync: false
